repository: worldbuilding/worldbuilding.github.io

# Top of page
topnav_title: /r/Worldbuilding

# <title>
site_title: /r/Worldbuilding Network

# footer
company_name: /r/worldbuilding network moderators and contributors

github_editme_path: worldbuilding/KazTron/blob/gh-pages

# for disqus comments
disqus_shortname:

# if you have google-analytics ID, put it in. if not, edit this value to blank.
google_analytics:

# the preview server used. Leave as is.
host: 127.0.0.1

# port where the preview is rendered. You can leave this as is unless you have other Jekyll builds
# using this same port that might cause conflicts. in that case, use another port such as 4006.
port: 4000

# these are the files and directories that jekyll will exclude from the build
exclude:
  - .idea/
  - .gitignore
  - "*.sublime-*"
  - "*.sh"
  - createtag
  - licenses/
  - examples/

plugins:
  - jekyll-redirect-from

# feedback_subject_line: 

# used as a contact email for the Feedback link in the top navigation bar
# feedback_email: 

# if you uncomment this line, the Feedback link gets removed
#feedback_disable: true

# if you uncomment this line, it changes the Feedback text
# feedback_text: "Need help?"

# if you uncomment this line, it changes where the feedback link points to
feedback_link: "https://www.reddit.com/message/compose?to=%2Fr%2Fworldbuilding&subject=worldbuilding.network&message=I'm writing to you about KazTron.%0D%0D<Type your comments here>"

# library used for syntax highlighting
highlighter: rouge

# filter used to process markdown. note that kramdown differs from github-flavored markdown in some subtle ways
markdown: kramdown
kramdown:
 input: GFM
 auto_ids: true
 hard_wrap: false
 syntax_highlighter: rouge

# collections are declared here. this renders the content in _tooltips and processes it, but doesn't output it as actual files in the output unless you change output to true
collections:
  tooltips:
    output: false

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      comments: false
      search: true
      sidebar: home
      topnav: topnav
  -
    scope:
      path: "20"
      type: "pages"
    values:
      layout: "page"
      comments: false
      search: true
      sidebar: kaztron-20
      topnav: topnav
  -
    scope:
      path: "21"
      type: "pages"
    values:
      layout: "page"
      comments: false
      search: true
      sidebar: kaztron-21
      topnav: topnav
  -
    scope:
      path: "22"
      type: "pages"
    values:
      layout: "page"
      comments: false
      search: true
      sidebar: kaztron-22
      topnav: topnav
  -
    scope:
      path: "dev"
      type: "pages"
    values:
      layout: "page"
      comments: false
      search: true
      sidebar: kaztron-dev
      topnav: topnav
  -
    scope:
      path: ""
      type: "tooltips"
    values:
      layout: "page"
      comments: false
      search: true
      tooltip: true
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
      search: true
      sidebar: home
      topnav: topnav

# these are defaults used for the frontmatter for these file types

sidebars:
- home
- kaztron-20
- kaztron-21
- kaztron-22
- kaztron-dev
- other

# the description is used in the feed.xml file
description: >
  Resources for the /r/worldbuilding community - for now mostly in-house software resources.

# needed for sitemap.xml file only
url: http://worldbuilding.network
baseurl: "/kaztron"
